### ISSUE TITLE
Document time value units

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-configuration#29]
The time units (i.e. timeout/interval) are listed in kitchen sink example, but there's no unit information. Would be nice to add information regarding what that unit is.

**Comment by jaydeluca** [comment]
If you are looking for contributors I would be interested in helping with this. Would the general idea be to identify all values that are a time  and augment their description with the unit, for example:

from 
```
# Configure delay interval between two consecutive exports.
#
# Environment variable: OTEL_BLRP_SCHEDULE_DELAY
schedule_delay: 5000
```

to something like
```
# Configure delay interval (in milliseconds) between two consecutive exports.
#
# Environment variable: OTEL_BLRP_SCHEDULE_DELAY
schedule_delay: 5000
```

Or would there be another format that would be more preferable?

**Comment by codeboten** [comment]
Thanks @jaydeluca, i think something like that would work
