### ISSUE TITLE
Decide if we should add jaeger exporter schema to SpanExporter

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-configuration#42]
Since the jaeger span exporter was deprecated and removed form the specification, the jaeger parameters no longer exist in the [environment variable scheme](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md).

Presumably that means we should add jaeger to the file configuration schema, but want to confirm. 

https://github.com/open-telemetry/opentelemetry-configuration/blob/979a4817216eee572d8b2689130f4421887eb571/schema/tracer_provider.json#L136-L142

**Comment by codeboten** [comment]
Decided in the Sept 18 meeting that we won't add it for now, we can always add it back later if needed.
