### ISSUE TITLE
Release 0.1.0-alpha

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-configuration#46]
We've made a lot of progress defining the schema and implementing prototypes in java and go (for the collector).

Its time to think about the first release, so prototype implementations can have something concrete to point to instead of the SHA of a commit on the main branch.

This issue is to discuss any prerequisites needed for a `0.1.0-alpha` release. 

- [x] Define release process
- [x] Identify any issues we want to resolve before release

**Comment by codeboten** [comment]
I'll put together a release doc and open a PR

**Comment by codeboten** [comment]
Are there any issues pending that would block the release of v0.1? @jack-berg @MrAlias

**Comment by jack-berg** [comment]
None that I know of. Let's check the box and do the release 👍

**Comment by codeboten** [comment]
This is now complete 🎉
