### ISSUE TITLE
[security] audit repository tooling

### ISSUE THREAD

**Issue by EjiroLaurelD** [open-telemetry/opentelemetry-configuration#52]
Hello,
The Security SIG is looking to ensure that security tooling is setup consistently across the organization. As a result, we're asking maintainers to ensure the following tools are enabled in each repository:

- [x] CodeQL enabled via [GitHub Actions](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/workflows/codeql-analysis.yml)
- [x] Static code analysis tool (the collector uses govulncheck [https://pkg.go.dev/golang.org/x/vuln] on every build)
- [x]  Repository security settings
    - [x] Security Policy ✅
    - [x] Security advisories ✅
    - [x] Private vulnerability reporting ✅
    - [x] Dependabot alerts ✅
    - [x] Code scanning alerts ✅

Parent issue: https://github.com/open-telemetry/sig-security/issues/12

**Comment by jaydeluca** [comment]
Just a note, since there is no functional code in this repository, CodeQL will not apply (I tested what it would do and it results in the github action failing with the error `CodeQL did not detect any code written in languages supported by CodeQL.`). The same for Static code analysis.

**Comment by tsloughter** [comment]
I thought most Otel repos has moved to renovate from dependabot? Can either be used?

**Comment by codeboten** [comment]
> I thought most Otel repos has moved to renovate from dependabot? Can either be used?

This is true for dependency management, dependabot is still used for security alerts though

**Comment by codeboten** [comment]
The last item (govulncheck) was addressed, marking this issue closed
