### ISSUE TITLE
Default config file template that incorporates standard env vars

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-configuration#55]
Consider publishing/maintaining a default template that contains all the standard environment variables being mapped to the file config equivalent.

I think this would be important to enable users with complex env var config setup to successfully migrate to file config.

**Comment by codeboten** [comment]
Thanks for the issue @tylerbenson, i like this idea, we could take https://github.com/open-telemetry/opentelemetry-configuration/blob/main/examples/kitchen-sink.yaml as a starting point and use the environment variables that are already documented there.
