### ISSUE TITLE
Additional Prometheus exporter configuration options

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-configuration#59]
The Prometheus exporter in Go exposes certain options that are necessary to be able to move forward with supporting configuration in the OpenTelemetry collector. These options are listed here: https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/prometheus/config.go

The question I have is whether we should add options for these in the config schema.

**Comment by jack-berg** [comment]
I know we've made some progress on this.. are there any important prometheus properties which still aren't part of the schema? As of now we have:
- host
- port
- without_units
- without_type_suffix
- without_scope_info
- with_resource_constant_labels

**Comment by codeboten** [comment]
I believe all the necessary options have been added. I'll open follow up issues for any individual configurations if that's not the case.
