### ISSUE TITLE
SDK enabled/disabled

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-configuration#7]
Which should we use?

**Comment by pirgeo** [comment]
I would assume that most people that set up a config file to configure the SDK would expect it to be enabled by default. Having to set enabled would mean `enabled: true` has to be part of every config file.

**Comment by MrAlias** [comment]
> I would assume that most people that set up a config file to configure the SDK would expect it to be enabled by default. Having to set enabled would mean `enabled: true` has to be part of every config file.

Right, this motivates the use of the term "disabled'.
