### ISSUE TITLE
Define processors/exporters relationship

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-configuration#8]
Are exporters nested in processors?

**Comment by jack-berg** [comment]
Yes. We've adopted a pattern of directly defining complex types as properties of their containing types. Examples:

- PeriodicMetricReader [has exporter field of type MetricExporter](https://github.com/open-telemetry/opentelemetry-configuration/blob/0508846f82ed54b230fa638e1e7556c52efee25e/schema/meter_provider.json#L34-L36)
- BatchSpanProcessor [has exporter field of type SpanExporter](https://github.com/open-telemetry/opentelemetry-configuration/blob/0508846f82ed54b230fa638e1e7556c52efee25e/schema/tracer_provider.json#L43-L45)
- LogRecordBatchProcessor [has exporter field of type LogRecordExporter](https://github.com/open-telemetry/opentelemetry-configuration/blob/0508846f82ed54b230fa638e1e7556c52efee25e/schema/logger_provider.json#L51-L53)
- ParentBased sampler [has properties of type Sampler](https://github.com/open-telemetry/opentelemetry-configuration/blob/0508846f82ed54b230fa638e1e7556c52efee25e/schema/tracer_provider.json#L85-L99)
