### ISSUE TITLE
CLI to expand variables, validate and export to json (or yaml) 

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-configuration#86]
I've created https://github.com/tsloughter/otel_config_validator which I think should be considered for inclusion as part of this repo. I figured I'd create a separate repo and open an issue instead of a PR to discuss if it belongs and if it does, does it belong here or one of the otel tools repos.

**Comment by jack-berg** [comment]
Discussed in the 5/13/24 config SIG. Decided it makes sense to have the code for this component to live in this repository, as the build for this does a similar thing today and it makes sense to dogfood the tools we publish for users. We can publish binaries and a dockerized version of this type of tool, using versioning which is independent from the configuration scheme itself.
